"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.conf.global_settings import LOGIN_REDIRECT_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
env = environ.Env()
if (BASE_DIR / ".env").exists():
    environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "src.authentication",
    "src.users",
    "src.safe",
    "config_celery",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password policy aligned with OWASP ASVS 4.0 (length >= 12, complexity,
# rejection of popular/leaked passwords, no purely numeric passwords).
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "src.authentication.passwords.PasswordComplexityValidator",
        "OPTIONS": {"min_classes": 3},
    },
    {
        # Checks against the bundled local wordlist of popular passwords.
        "NAME": "src.authentication.passwords.CommonPasswordValidator",
    },
]

# Argon2id work factors. Defaults follow (and exceed) the OWASP minimum;
# tune via .env without code changes.
ARGON2_TIME_COST = env.int("ARGON2_TIME_COST", default=3)
ARGON2_MEMORY_COST = env.int("ARGON2_MEMORY_COST", default=65536)  # KiB (= 64 MiB)
ARGON2_PARALLELISM = env.int("ARGON2_PARALLELISM", default=4)

# Single argon2 hasher: the subclass verifies any existing argon2 hash (the
# cost parameters are embedded in each hash) while writing new hashes with our
# configured work factors. Listing the stock hasher too would shadow ours,
# since both register under the "argon2" algorithm name.
PASSWORD_HASHERS = [
    "src.authentication.hashers.ConfigurableArgon2PasswordHasher",
]

# Account lockout after repeated failed logins.
LOGIN_FAILURE_LIMIT = env.int("LOGIN_FAILURE_LIMIT", default=3)
LOGIN_FAILURE_LOCKOUT_SECONDS = env.int("LOGIN_FAILURE_LOCKOUT_SECONDS", default=60)
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pl"

TIME_ZONE = "UTC"

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

RECAPTCHA_SITE_KEY = env("RECAPTCHA_SITE_KEY")
RECAPTCHA_SECRET_KEY = env("RECAPTCHA_SECRET_KEY")

# Issuer label shown in the user's authenticator app (Google Authenticator).
TOTP_ISSUER_NAME = env("TOTP_ISSUER_NAME")
INVITATION_TOKEN_MAX_AGE_SECONDS = env.int(
    "INVITATION_TOKEN_MAX_AGE_SECONDS", default=7 * 24 * 60 * 60
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_PROFILE_MODULE = "users.Users"
AUTH_USER_MODEL = "users.Users"
AUTH_USER_ADMIN_MODEL = "user.CustomUserAdmin"

AUTHENTICATION_BACKENDS = [
    "src.authentication.authentication.EmailAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]
PHONENUMBER_DEFAULT_REGION = "PL"

SESSION_EXPIRE_SECONDS = 604800
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_TIMEOUT_REDIRECT = "/"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = env("CELERY_TIMEZONE")
CELERY_TASK_TRACK_STARTED = env("CELERY_TASK_TRACK_STARTED")
CELERY_TASK_TIME_LIMIT = env("CELERY_TASK_TIME_LIMIT")

LOGGING = {
    "version": 1,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

LOGIN_URL = "authentication:login"
LOGIN_REDIRECT_URL = "authentication:service_home"